Object Oriented Programming Practice : StandardScaler Implementation
===
B036060017 資管四年級 謝威廷

## Example : sklearn StandardScaler
- [Official Documents](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [1]:
from sklearn.preprocessing import StandardScaler

data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [3]:
scaler.mean_

array([ 0.5,  0.5])

In [4]:
scaler.var_

array([ 0.25,  0.25])

In [5]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [6]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

## Handcrafted StandardScaler

In [7]:
import numpy as np

class myStandardScaler():
    def __init__(self):
        self.mean_ = None
        self.var_ = None
        
    def fit(self, data):
        self.mean_ = np.mean(data, axis=0)
        self.var_ = np.var(data, axis=0)
    
    def transform(self, data):
        return (data - self.mean_) / np.sqrt(self.var_)
        
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [8]:
myscaler = myStandardScaler()
myscaler.fit(data)

In [9]:
myscaler.mean_

array([ 0.5,  0.5])

In [10]:
myscaler.var_

array([ 0.25,  0.25])

In [11]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [12]:
myscaler.transform([2, 2])

array([ 3.,  3.])

In [13]:
myscaler.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])